import { rollAttrib } from "../helpers/diceroll.mjs";
import * as argpUtils from "../helpers/utils.mjs";
import TOTOWActiveEffect from "../documents/active-effect.mjs";

/** Maps a critical injury roll total to the modifiers it applies. */
const CRIT_MODIFIERS = {
  11: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' },
       { name: 'TALESOFTHEOLDWEST.Ability.Fightin.listName',     value: '-1', state: 'Active' }],
  14: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' },
       { name: 'TALESOFTHEOLDWEST.Ability.Fightin.listName',     value: '-1', state: 'Active' }],
  12: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' }],
  21: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' }],
  23: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' }],
  41: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' }],
  51: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-1', state: 'Active' }],
  22: [{ name: 'TALESOFTHEOLDWEST.Ability.Resilience.listName',  value: '-1', state: 'Active' }],
  44: [{ name: 'TALESOFTHEOLDWEST.Ability.Resilience.listName',  value: '-1', state: 'Active' }],
  31: [{ name: 'TALESOFTHEOLDWEST.Ability.Shootin.listName',     value: '-1', state: 'Active' }],
  32: [{ name: 'TALESOFTHEOLDWEST.Ability.Shootin.listName',     value: '-1', state: 'Active' },
       { name: 'TALESOFTHEOLDWEST.Ability.Fightin.listName',     value: '-1', state: 'Active' }],
  52: [{ name: 'TALESOFTHEOLDWEST.Ability.Move.listName',        value: '-2', state: 'Active' }],
  61: [{ name: 'TALESOFTHEOLDWEST.Ability.Performin.listName',   value: '-1', state: 'Active' }],
  62: [{ name: 'TALESOFTHEOLDWEST.Ability.Labor.listName',       value: '-1', state: 'Active' }],
  63: [{ name: 'TALESOFTHEOLDWEST.Ability.Shootin.listName',     value: '-2', state: 'Active' },
       { name: 'TALESOFTHEOLDWEST.Ability.Hawkeye.listName',     value: '-2', state: 'Active' }],
};

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class totowActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  // /** @override */
  // prepareBaseData() {
  //   // Data modifications in this step occur before processing embedded
  //   // documents or derived data.
  // }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const systemData = actorData.system;
    const flags = actorData.flags.talesoftheoldwest || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    let spanner = { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
    spanner.actorType = this.type;

    // Build itemMods so that prepModOutput can surface Conditional modifiers
    // at roll time. This mirrors what _prepareItems does on the sheet.
    const itemMods = [];
    for (const i of this.items) {
      argpUtils.findMods(i, itemMods);
    }
    spanner.itemMods = Object.groupBy(itemMods, ({ name }) => name);

    return spanner;
  }
  // *************************************************
  // Setupthe prototype token
  // *************************************************
  async _preCreate(data, options, user) {
    await super._preCreate(data, options, user);
    let tokenProto = {
      "prototypeToken.displayName": CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      "prototypeToken.displayBars": CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
      "prototypeToken.disposition": CONST.TOKEN_DISPOSITIONS.FRIENDLY,
      "prototypeToken.name": `${data.name}`,
      "prototypeToken.bar1": { attribute: "header.health" },
      "prototypeToken.bar2": { attribute: "None" },
      // 'prototypeToken.vision': true,
      "prototypeToken.actorLink": true,
      "prototypeToken.sight.enabled": "true",
      "prototypeToken.sight.range": "12",
    };
    switch (data.type) {
      case "pc":
        tokenProto["prototypeToken.bar2"] = { attribute: "header.stress" };
        break;
      case "npc":
        tokenProto["prototypeToken.actorLink"] = false;
        tokenProto["prototypeToken.disposition"] = CONST.TOKEN_DISPOSITIONS.HOSTILE;
        tokenProto["prototypeToken.sight.enabled"] = false;
        break;
    }
    // }

    this.updateSource(tokenProto);
    // this.updateSource(createData);
  }

  /**
   * Toggle a configured status effect for the Actor.
   * @param {string} statusId       A status effect ID defined in CONFIG.statusEffects.
   * @param {object} [options={}]   Additional options which modify how the effect is created.
   * @param {boolean} [options.active]          Force the effect to be active or inactive regardless of its current state.
   * @param {boolean} [options.overlay=false]   Display the toggled effect as an overlay.
   * @param {string} [options.effectEnd]        Value for `system.end.type`.
   * @returns {PromiseAlienRPGActiveEffect|boolean|undefined>}  A promise which resolves to one of the following values:
   *                                 - ActiveEffect if a new effect need to be created
   *                                 - true if was already an existing effect
   *                                 - false if an existing effect needed to be removed
   *                                 - undefined if no changes need to be made.
   * @override Implementation copied from core.
   */
  async toggleStatusEffect(statusId, { active, overlay = false, effectEnd = "" } = {}) {
    const status = CONFIG.statusEffects.find((e) => e.id === statusId);
    if (!status) throw new Error(`Invalid status ID "${statusId}" provided to Actor#toggleStatusEffect`);
    const existing = [];
    const hitList = [];
    // const lastRoll = this.system.general.panic.lastRoll

    // Find the effect with the static _id of the status effect
    if (status._id) {
      const effect = this.effects.get(status._id);
      if (effect) existing.push(effect.id);
    }
    // If no static _id, find all single-status effects that have this status
    else {
      for (const effect of this.effects) {
        const statuses = effect.statuses;
        if (statuses.size === 1 && statuses.has(status.id)) existing.push(effect.id);
      }
    }

    // Remove the existing effects unless the status effect is forced active
    if (existing.length) {
      if (active) return true;
      await this.deleteEmbeddedDocuments("ActiveEffect", existing);
      return false;
    }

    // Create a new effect unless the status effect is forced inactive
    if (!active && active !== undefined) return;
    const effect = await TOTOWActiveEffect.fromStatusEffect(statusId);
    if (overlay) effect.updateSource({ "flags.core.overlay": true });
    if (effectEnd) effect.updateSource({ "system.end.type": effectEnd });
    return TOTOWActiveEffect.create(effect, { parent: this, keepId: true });
  }

  async addCondition(effect) {
    if (typeof effect === "string") {
      effect = foundry.utils.duplicate(CONFIG.TALESOFTHEOLDWEST.conditionEffects.find((e) => e.id == effect));
    }
    if (!effect) return "No Effect Found";
    if (!effect.id) return "Conditions require an id field";

    let existing = await this.hasCondition(effect.id);
    if (!existing) {
      effect.label = game.i18n.localize(effect.label).replace(/(^\w{1})|(\s+\w{1})/g, (letter) => letter.toUpperCase());
      effect.name = game.i18n.localize(effect.name).replace(/(^\w{1})|(\s+\w{1})/g, (letter) => letter.toUpperCase());
      effect["statuses"] = effect.id;
      delete effect.id;
      return await this.createEmbeddedDocuments("ActiveEffect", [effect]);
    }
  }

  async removeCondition(effect) {
    if (typeof effect === "string") {
      effect = foundry.utils.duplicate(CONFIG.TALESOFTHEOLDWEST.conditionEffects.find((e) => e.id == effect));
    }
    if (!effect) return "No Effect Found";
    if (!effect.id) return "Conditions require an id field";
    let existing = await this.hasCondition(effect.id);
    if (existing) {
      return await this.deleteEmbeddedDocuments("ActiveEffect", [existing._id]);
    }
  }
  async hasCondition(conditionKey) {
    let existing = "";
    existing = this.effects.find((effect) => effect.statuses.has(conditionKey));
    return existing;
  }

  async rollCrit(actor, type, dataset, manCrit) {
    let cFatal = false;
    let fatal = [];
    let rollFatal = "";
    let newFatalTime = "";
    let atable = "";
    let testArray = "";
    let rollheal = "";
    let newHealTime = "";
    let htmlData = "";
    let resultImage = "";
    let diceRoll = "";
    let update = {};
    let noMods = "";

    switch (type) {
      case "pc":
        // case 'npc':
        atable = game.tables.getName(game.i18n.localize("TALESOFTHEOLDWEST.CriticalInjuries")) || game.tables.getName("Critical Injuries");
        if (atable === null || atable === undefined) {
          ui.notifications.warn(game.i18n.localize("TALESOFTHEOLDWEST.NoCharCrit"));
          return;
        }

        break;
      default:
        return;
    }

    if (!manCrit) {
      diceRoll = await atable.draw({ displayChat: false });
    } else {
      const formula = manCrit;
      const roll = await new Roll(formula).evaluate();
      diceRoll = await atable.draw({ roll: roll, displayChat: false });
    }
    let messG = diceRoll.results[0].description;
    switch (type) {
      case "pc":
      case "npc":
        {
          resultImage = diceRoll.results[0].img;
          // Parse structured critical injury fields with robust regex matching
          const extractField = (label) => {
            const pattern = new RegExp(`<strong>${label}</strong>:\\s*([\\s\\S]*?)(?=(?:<p><strong>|<\\/p>|$))`, "i");
            const match = pattern.exec(messG);
            return match ? match[1].replace(/<\/?[^>]+(>|$)/g, "").trim() : "";
          };

          const rawLocation = extractField("Location") || "Body";
          const rawInjury = extractField("Injury") || "Critical Injury";
          const rawFatal = extractField("Fatal") || "No";
          let rawHealingTime = extractField("Healing Time") || "-";
          const rawImmediate = extractField("Immediate Effect") || "None";
          let rawLongTerm = extractField("Long-Term Effect") || extractField("Long Term Effect") || "None";

          // Retain testArray structure for backwards-compatibility with downstream variable usage
          testArray = [
            "Location", rawLocation,
            "Injury", rawInjury,
            "Fatal", rawFatal,
            "Healing Time", rawHealingTime,
            "Immediate Effect", rawImmediate,
            "Long-Term Effect", rawLongTerm,
          ];

          // Process Fatal
          const isFatalYes = /^yes/i.test(rawFatal);
          if (isFatalYes) {
            cFatal = true;
            if (/instant/i.test(rawFatal)) {
              fatal = ["YES", "Instant"];
              fatal[0] =
                '<strong style="color: red;">' + fatal[0] + "</strong><br>" + game.i18n.localize("TALESOFTHEOLDWEST.Criticals.endOfTheTrail");
              testArray[11] = '<strong style="color: red;">' + testArray[11] + "</strong>";
            } else {
              const fatalDiceMatch = rawFatal.match(/\[\[([0-9]+d[0-9]+)\]\]\s*(.*)/i);
              if (fatalDiceMatch) {
                rollFatal = fatalDiceMatch[1];
                newFatalTime = fatalDiceMatch[2] || "";
                const evalRoll = (await new Roll(`${rollFatal}`).evaluate()).result;
                fatal = ["YES", `${evalRoll} ${newFatalTime}`.trim()];
              } else {
                fatal = ["YES", rawFatal];
              }

              const hasPenalty = /[-−]1/i.test(rawFatal);
              if (hasPenalty) {
                fatal[0] =
                  '<strong style="color: red;">' +
                  game.i18n.localize("TALESOFTHEOLDWEST.General.yes").toUpperCase() +
                  "</strong><br>" +
                  game.i18n.localize("TALESOFTHEOLDWEST.Criticals.rollResilience") +
                  fatal[1] +
                  "<br> -1 to <strong>" +
                  game.i18n.localize("TALESOFTHEOLDWEST.Ability.Doctorin.long") +
                  "</strong> roll.";
              } else {
                fatal[0] =
                  '<strong style="color: red;">' +
                  game.i18n.localize("TALESOFTHEOLDWEST.General.yes").toUpperCase() +
                  "</strong><br>" +
                  game.i18n.localize("TALESOFTHEOLDWEST.Criticals.rollResilience") +
                  fatal[1];
              }
            }
          } else {
            cFatal = false;
            fatal = [game.i18n.localize("TALESOFTHEOLDWEST.General.no"), ""];
          }

          // Process Healing Time
          if (rawHealingTime && rawHealingTime !== "-" && !/instant/i.test(rawFatal)) {
            const healDiceMatch = rawHealingTime.match(/\[\[([0-9]+d[0-9]+)\]\]\s*(.*)/i);
            if (healDiceMatch) {
              rollheal = healDiceMatch[1];
              newHealTime = healDiceMatch[2] || "";
              testArray[7] = (await new Roll(`${rollheal}`).evaluate()).result + " " + newHealTime;
            } else {
              testArray[7] = rawHealingTime;
            }
          } else {
            testArray[7] = game.i18n.localize("TALESOFTHEOLDWEST.ItemModifierSelect.none");
          }

          // Setup Modifiers
          const critMods = CRIT_MODIFIERS[diceRoll.roll._total];
          if (critMods) {
            critMods.forEach((mod, i) => {
              update[`system.itemModifiers.[${i}]`] = {
                name: game.i18n.localize(mod.name),
                value: mod.value,
                state: mod.state,
              };
            });
          } else {
            noMods = true;
          }

          //
          // Now create the item on the sheet
          //

          let rollData = {
            type: "crit",
            img: resultImage,
            name: `#${diceRoll.roll._total} ${testArray[1]} - ${testArray[3]}`,
            "system.location": testArray[1].toLowerCase().replace(/\s/g, ""),
            "system.injury": testArray[3],
            "system.healingtime": testArray[7],
            "system.fatal": cFatal,
            "system.fatalmessage": fatal[0].replace(/(YES)\s/g, ""),
            "system.imediateeffect": testArray[9],
            "system.longtermeffect": testArray[11],
          };

          const theItem = await this.createEmbeddedDocuments("Item", [rollData]);

          //
          // Now add the Modifiers if there are any
          //
          if (!noMods) {
            await theItem[0].update(update);
          }

          //)
          // Prepare the data for the chat message
          //

          htmlData = {
            actorname: actor.name,
            img: resultImage,
            name: `#${diceRoll.roll._total} ${testArray[1]}`,
            injury: testArray[3],
            fatal: fatal[0],
            healingtime: testArray[7],
            imediateeffect: testArray[9],
            longtermeffect: testArray[11],
            manCrit: manCrit,
          };
        }
        break;
    }

    // Now push the correct chat message
    const html = await foundry.applications.handlebars.renderTemplate(`systems/talesoftheoldwest/templates/chat/crit-roll-${actor.type}.hbs`, htmlData);
    let chatData = {
      user: game.user.id,
      speaker: {
        actor: actor.id,
      },
      content: html,
      other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
      sound: CONFIG.sounds.dice,
    };

    // Apply the Active Effect

    switch (type) {
      case "pc":
        // case 'npc':
        if (actor.system.critInj.length === 1) {
          this.toggleStatusEffect("criticalinj");
        }
        break;
      // case 'creature':criticalinj
      // 	break;

      default:
        break;
    }

    ChatMessage.applyMode(chatData, game.settings.get("core", "rollMode"));
    return ChatMessage.create(chatData);
  }

  async rollCritMan(actor, type, dataset) {
    const content = await foundry.applications.handlebars.renderTemplate(
      "systems/talesoftheoldwest/templates/dialog/roll-char-manual-crit-dialog.html",
      actor,
      type,
      dataset,
    );
    const response = await foundry.applications.api.DialogV2.wait({
      window: { title: "TALESOFTHEOLDWEST.dialog.RollManCrit" },
      content,
      rejectClose: false,
      buttons: [
        {
          label: "TALESOFTHEOLDWEST.dialog.roll",
          callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
        },
        {
          label: "TALESOFTHEOLDWEST.dialog.cancel",
          action: "cancel",
        },
      ],
    });
    if (!response || response === "cancel") return "cancelled";
    if (!response.manCrit.match(/^[1-6]?[1-6]$/gm)) {
      ui.notifications.warn(game.i18n.localize("TALESOFTHEOLDWEST.dialog.RollManCharCrit"));
      return;
    }
    await actor.rollCrit(actor, type, dataset, response.manCrit);
  }

  async diceRoll(actor, event, target) {
    let config = CONFIG.TALESOFTHEOLDWEST;

    event.preventDefault(); // Don't open context menu
    event.stopPropagation(); // Don't trigger other events
    if (event.detail > 1) return; // Ignore repeated clicks
    const rollData = this.getRollData();
    const dataset = target.dataset;
    dataset.myHorse = "false";
    // const targetActor = actor.getRollData();
    if (actor.type === "pc") {
      dataset.faithpoints = actor.system.general.faithpoints.value;
      dataset.canPush = actor.system.general.canPush;
    } else {
      dataset.faithpoints = 0;
      dataset.canPush = false;
    }

    dataset.myActor = actor.id;
    let result = "";

    // Handle item rolls.
    if (dataset.rollType) {
      if (dataset.rollType === "attribute" || dataset.rollType === "ability") {
        switch (dataset.rollType) {
          case "attribute":
            result = await processConditionals("Attributes", dataset, rollData);
            break;
          case "ability":
            if (dataset.label === game.i18n.localize("TALESOFTHEOLDWEST.Ability.Animalhandlin.long") && actor.type == "pc") {
              if (actor.system.remuda.remudaMounted !== "false") {
                let horse = await this.getRemuda(actor.system.remuda.remudaMounted);
                const content = await foundry.applications.handlebars.renderTemplate("systems/talesoftheoldwest/templates/dialog/riding-my-horse.hbs", horse);
                const response = await foundry.applications.api.DialogV2.confirm({
                  window: { title: "TALESOFTHEOLDWEST.dialog.Ride-My-Horse-Dialog" },
                  content,
                  modal: true,
                });
                if (response === true) {
                  dataset.myHorse = "true";
                  dataset.mod = Number(dataset.mod) + Number(horse.actor.system.general.ridingmodifier.value);
                }
              }
            }
            result = await processConditionals("Abilities", dataset, rollData);
            break;
          default:
            break;
        }
      } else {
        const itemId = target.dataset.itemId;
        const item = actor.items.get(itemId);
        switch (dataset.rollType) {
          case "item":
            // case 'talent':
            return item.roll(dataset);
          case "weapon":
            result = await item.roll(dataset, item);
          default:
            break;
        }
      }
      if (result === "cancelled") {
        return;
      } else {
        sendToChat(actor, event, target, result);
      }

      async function processConditionals(rollType, dataset, rollData) {
        let response = "";
        const { conditionalMods, talentMods } = await argpUtils.prepModOutput(rollType, rollData, dataset);
        if (conditionalMods?.length || talentMods?.length) {
          const content = await foundry.applications.handlebars.renderTemplate("systems/talesoftheoldwest/templates/dialog/conditional-modifiers.html", {
            config,
            dataset,
            conditionalMods,
            talentMods,
          });
          response = await foundry.applications.api.DialogV2.wait({
            window: { title: "TALESOFTHEOLDWEST.Item.General.roll-modifiers" },
            content,
            rejectClose: false,
            buttons: [
              {
                label: "TALESOFTHEOLDWEST.dialog.roll",
                callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
              },
              {
                label: "TALESOFTHEOLDWEST.dialog.cancel",
                action: "cancel",
              },
            ],
          });

          if (!response || response === "cancel") return "cancelled";

          // Accumulate checked conditional modifiers (mods.* flat keys from structured partial).
          // FormDataExtended stores dot-notation names as flat string keys, not nested objects,
          // so `response["mods.f_0"]` exists but `response.mods` is undefined.
          const checkboxSum = Object.entries(response)
            .filter(([k]) => k.startsWith('mods.'))
            .reduce((sum, [, v]) => sum + (Number(v) || 0), 0);

          dataset.mod = parseInt(dataset.mod || 0) + checkboxSum;
        }

        result = await rollAttrib(dataset, rollData, actor);
        return result;
      }

      async function sendToChat(actor, event, target, result) {
        const html = await foundry.applications.handlebars.renderTemplate("systems/talesoftheoldwest/templates/chat/roll.hbs", result.result);
        let chatData = {
          user: game.user.id,
          speaker: ChatMessage.getSpeaker({
            alias: actor.name,
            actor: actor.id,
          }),
          rolls: [result.roll],
          rollMode: game.settings.get("core", "rollMode"),
          content: html,
          sound: CONFIG.sounds.dice,
          // flags: {talesoftheoldwest:	[{'isType': actor.type}]}
        };
        if (["gmroll", "blindroll"].includes(chatData.rollMode)) {
          chatData.whisper = ChatMessage.getWhisperRecipients("GM");
        } else if (chatData.rollMode === "selfroll") {
          chatData.whisper = [game.user];
        }
        const msg = await ChatMessage.create(chatData);
        result.result.messageNo = msg.id;
        await msg.setFlag("talesoftheoldwest", "results", result);
        await msg.setFlag("talesoftheoldwest", "isType", actor.type);

        return result;
      }
    }
    this.render();
  }

  async modRoll(actor, event, target) {
    const content = await foundry.applications.handlebars.renderTemplate("systems/talesoftheoldwest/templates/dialog/roll-modifier.html", actor, event, target);
    const response = await foundry.applications.api.DialogV2.wait({
      window: { title: "TALESOFTHEOLDWEST.Item.General.roll-modifiers" },
      content,
      rejectClose: false,
      buttons: [
        {
          label: "TALESOFTHEOLDWEST.dialog.roll",
          callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
        },
        {
          label: "TALESOFTHEOLDWEST.dialog.cancel",
          action: "cancel",
        },
      ],
    });
    if (!response || response === "cancel") return "cancelled";
    target.dataset.mod = Number.parseInt(target.dataset.mod || 0) + Number.parseInt(response.manMod || 0);

    await actor.diceRoll(actor, event, target);
  }

  async createChatMessage(message, actorID) {
    let chatData = {
      user: game.user.id,
      speaker: {
        actor: actorID,
      },
      content: new Handlebars.SafeString(message),
      other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
      sound: CONFIG.sounds.lock,
    };

    ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"));
    return ChatMessage.create(chatData);
  }

  /* ------------------------------------------- */
  /*  linked actors Management                   */
  /* ------------------------------------------- */

  /**
   * @param {string}  compId              The id of the added actor
   * @returns {details}
   */
  async addCompadres(compId) {
    if (this.type !== "pc") return;

    const system = this.system;
    const details = {
      id: compId,
    };
    // Removes duplicates.
    if (system.compadres.details.some((o) => o.id === compId)) this.removeCompadres(compId);
    // Adds the new occupant.
    system.compadres.details.push(details);
    await this.update({ "system.compadres.details": system.compadres.details });

    await this.update({ "system.compadres.compadresQty": system.compadres.details.length });

    return details;
  }

  /* ------------------------------------------- */

  /**
   * @param {string} compId The id of the occupant to remove
   * @return {Compadres[]}
   */
  removeCompadres(compId) {
    if (this.type !== "pc") return;
    const compadres = this.system.compadres;
    compadres.details = compadres.details.filter((o) => o.id !== compId);
    return compadres.details;
  }

  /* ------------------------------------------- */

  /**
   * @param {string} compId The id of the occupant to find
   * @returns {VehicleOccupant|undefined}
   */
  getCompadres(compId) {
    if (this.type !== "pc") return;
    return this.system.compadres.details.find((o) => o.id === compId);
  }

  /* ------------------------------------------- */
  /**
   * @param {string}  compId              The id of the added actor
   * @returns {details}
   */
  async addRemuda(compId) {
    if (this.type !== "pc") return;

    const system = this.system;
    const details = {
      id: compId,
    };
    // Removes duplicates.
    if (system.remuda.details.some((o) => o.id === compId)) this.removeRemuda(compId);
    // Adds the new occupant.
    system.remuda.details.push(details);
    await this.update({ "system.remuda.details": system.remuda.details });

    await this.update({ "system.remuda.remudaQty": system.remuda.details.length });

    return details;
  }

  /* ------------------------------------------- */

  /**
   * @param {string} compId The id of the occupant to remove
   * @return {Remuda[]}
   */
  removeRemuda(compId) {
    if (this.type !== "pc") return;
    const remuda = this.system.remuda;
    remuda.details = remuda.details.filter((o) => o.id !== compId);
    return remuda.details;
  }

  /* ------------------------------------------- */

  /**
   * @param {string} compId The id of the occupant to find
   * @returns {VehicleOccupant|undefined}
   */
  async getRemuda(compId) {
    if (this.type !== "pc") return;
    const entry = this.system.remuda.details.find((o) => o.id === compId);
    if (!entry) return undefined;
    return {
      ...entry,
      actor: game.actors.get(entry.id),
    };
  }

  /**
   * Gets a collection of crewed actors.
   * @returns {Collection<string, Actor>} [id, actor]
   */
  getCrew() {
    if (this.type !== "pc") return undefined;
    const c = new foundry.utils.Collection();
    for (const o of this.system.compadres.details) {
      c.set(o.id, game.actors.get(o.id));
    }
    return c;
  }
}
